FROM node:18

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm install

COPY . .

ARG PORT_BACK=
ARG URL_FRONT=
ARG JWT_SECRET=
ARG JWT_SECRET_CLIENT=
ARG NODE_ENV=
ARG ACCESS_TOKEN_MERCADO_PAGO=
ARG CONNECTION_LIMIT=
ARG HOST=
ARG USER=
ARG PASSWORD=
ARG DATABASE=

ENV PORT_BACK=${PORT_BACK}
ENV URL_FRONT=${URL_FRONT}
ENV JWT_SECRET=${JWT_SECRET}
ENV JWT_SECRET_CLIENT=${JWT_SECRET_CLIENT}
ENV NODE_ENV=${NODE_ENV}
ENV ACCESS_TOKEN_MERCADO_PAGO=${ACCESS_TOKEN_MERCADO_PAGO}
ENV CONNECTION_LIMIT=${CONNECTION_LIMIT}
ENV HOST=${HOST}
ENV USER=${USER}
ENV PASSWORD=${PASSWORD}
ENV DATABASE=${DATABASE}

EXPOSE 3001

CMD ["npm", "start"]
